---
- name: Azure CLI Test
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Create container
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer05
      state: present
  
  - name: Upload file to Blob
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer05
      blob: test
      src: /tmp/test
      public_access: blob
