---
- name: Azure CLI Test
  #hosts: 192.168.1.181
  hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python3
  tasks:
  
  - name: Create container
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer05
      state: present
