---
- name: Azure CLI Test
  hosts: localhost
  tasks:
  
  - name: Create blob & file
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc04
      container: mytestcontainer03
      blob: testnow
      source: /tmp/testnow
      public_access: container
