---
- name: Azure CLI Test
  hosts: localhost
  tasks:
  
  - name: Create blob & file
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer03
      blob: text
      source: ./files/test
      public_access: container
