---
- name: Azure CLI Test
  hosts: 192.168.1.181
  #hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    client_id:
    secret:
    subscription_id:
    tenant:
  tasks:
  
  - name: Create container
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer06
      auth_source: auto
      state: present
