---
- name: Azure CLI Test
  hosts: 127.0.0.1
  connectoin: local
  tasks:
  
  - name: Create blob & file
    azure_rm_storageblob:
      resource_group: mytestrg01
      storage_account_name: myteststorageacc01
      container: mytestcontainer04
      blob: test
      src: '/tmp/test'
      public_access: container
