---
- name: GCP CLI Test
  hosts: 192.168.1.181
  tasks:
  
    #- name: List GCP Images
    #  command: gcloud compute images list
      
    - name: create instance template named foo
      gce_instance_template:
        name: foo
        size: n1-standard-1
        image_family: ubuntu-1604-lts
        state: present
        project_id: top-cab-265906
        credentials_file: /tmp/key.json
        service_account_email: admin-992@top-cab-265906.iam.gserviceaccount.com
