---
- name: GCP CLI Test
  hosts: localhost
  tasks:
  
    #- name: List GCP Images
    #  command: gcloud compute images list
      
    - name: create instance template named foo
      gce_instance_template:
        name: foo2
        size: n1-standard-1
        image_family: ubuntu-1604-lts
        state: present
        project_id: top-cab-265906
     #   credentials_file: '/tmp/key.json'
     #   service_account_email: admin-992@top-cab-265906.iam.gserviceaccount.com
   
    - name: Copy file to GCP bucket
      gcp_storage_object:
        action: upload
        bucket: onprem-images
        src: /tmp/test.txt
        project: top-cab-265906
        auth_kind: application

    - name: Copy file to GCP bucket2
      gc_storage:
        bucket: onprem-images
        src: /tmp/test.txt
        project: top-cab-265906
        auth_kind: application
        mode: put
    
    - name: Create test bucket
      gc_storage:
        bucket: test
        mode: create
