---
- name: GCP CLI Test
  hosts: 192.168.1.181
  tasks:
  
    - name: List GCP Images
      command: gcloud compute images list
      
- name: create a service account
  gcp_iam_service_account:
    name: test-ansible@top-cab-265906.iam.gserviceaccount.com
    display_name: My Ansible test key
    project: top-cab-265906
    auth_kind: application
    state: present
